#!/bin/bash

set -eu

XTERM_COLOURS=256
OUTFILE="${1-/dev/stdout}"

# According to ctlseqs.ms, [OSC]4;Pt␇ will return a name or RGB
# specification if Pt = '?'.
echo -ne '\e]4'
for n in $(seq 0 $(( XTERM_COLOURS - 1 )) ); do
    echo -n ";${n};?"
done
echo ''
echo 'You may need to hit enter here, not sure...' 1>&2

(for F in $(seq 0 $(( XTERM_COLOURS - 1 )) ); do \
    read -rsd $'\007'; \
    echo "${REPLY}"; \
done)\
    |tr -d "$(echo -ne '\e')]" \
    |sed -e "1i '(" \
         -e 's/^4;//g' \
         -e 's,$,/,g' \
         -e 's/;rgb:/ /g' \
         -e 's,\([0-9a-fA-F]\+\)/, #x\1,g' \
         -e 's/\(.*\)/(\1)/g' \
         -e '$a)' > ${OUTFILE}
          # ^--- Yikes!
